<?php
/**
 * Created by PhpStorm.
 * User: “崔鹏
 * Date: 2020/06/29
 * Time:  上午 9:46
 */

namespace app\friend\controller;

use app\admin\service\SysConfig;
use app\friend\service\FriendCircleCircle;
use app\friend\service\FriendCircleCommentEvaluate;
use app\friend\service\FriendCircleMessageReport;
use app\friend\service\FriendCircleTopic;
use bxkj_common\RedisClient;
use think\Db;
use think\facade\Request;

class Circle extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //读取config配置
        $redis       = new RedisClient();
        $cacheFriend = $redis->exists('cache:friend_config');
        if (empty($cacheFriend)) {
            $arr  = [];
            $ser  = new SysConfig();
            $info = $ser->getConfig("friend");
            if (empty($info)) return [];
            $redis->setex('cache:friend_config', 4 * 3600, $info['value']);
        }
        $friendConfigRes       = $redis->get('cache:friend_config');
        $this->friendConfigRes = json_decode($friendConfigRes, true);
    }

    public function index()
    {
        $this->checkAuth('friend:circle:index');
        $get         = input();
        $circleTopic = new  FriendCircleCircle();
        $total       = $circleTopic->getTotal($get);
        $page        = $this->pageshow($total);
        $list        = $circleTopic->getList($get, $page->firstRow, $page->listRows);
        $isRecom     = [['name' => '审核通过', 'value' => 1], ['name' => '待审核', 'value' => 0]];
        $this->assign('isRecom', json_encode($isRecom));
        $this->assign('_list', $list);
        return $this->fetch();
    }

    public function del()
    {
        $this->checkAuth('friend:circle:delete');
        $ids = get_request_ids();
        if (empty($ids)) $this->error('请选择记录');
        $msgComment = new FriendCircleCircle();
        $num        = $msgComment->del($ids);
        if (!$num) $this->error('关闭失败');
        alog("friend.circle.del", "删除圈子 ID：".implode(",", $ids));
        $count = count($ids);
        $this->success("关闭成功，共计关闭{$count}条记录");
    }

    public function edit()
    {
        if (Request::isGet()) {
            $id   = input('id');
            $info = Db::name('friend_circle_circle')->where('circle_id', $id)->find();
            if (empty($info)) $this->error('信息不存在');
            $this->assign('_info', $info);
            return $this->fetch('add');
        } else {
            $msgComment = new FriendCircleCircle();
            $post       = input();
            $result     = $msgComment->backstageedit($post);
            if (!$result) $this->error($msgComment->getError());
            alog("friend.circle.edit", "编辑圈子 ID：".$post['id']);
            $this->success('修改成功', $result);
        }
    }

    public function change_recom()
    {
        $this->checkAuth('friend:circle:change_recom');
        $ids = get_request_ids();
        if (empty($ids)) $this->error('请选择记录');
        $status = input('status');
        if (!in_array($status, ['0', '1'])) $this->error('状态值不正确');
        $friendnMsg = new FriendCircleCircle();
        $num        = $friendnMsg->changeRecom($ids, $status);
        if (!$num) $this->error('切换状态失败');
        alog("friend.circle.edit", "编辑圈子 ID：".implode(",", $ids)."<br>修改推荐状态".($status == 1 ? "推荐" : "普通"));
        $this->success('切换成功');
    }

    public function change_status()
    {
        $this->checkAuth('friend:circle:change_status');
        $ids = get_request_ids();
        if (empty($ids)) $this->error('请选择记录');
        $status = input('status');
        if (!in_array($status, ['0', '1'])) $this->error('状态值不正确');
        $friendnMsg = new FriendCircleCircle();
        $num        = $friendnMsg->changeStatus($ids, $status);
        if (!$num) $this->error('切换状态失败');
        alog("friend.circle.edit", "编辑圈子 ID：".implode(",", $ids)."<br>修改状态".($status == 1 ? "启用" : "禁用"));
        $this->success('切换成功');
    }

    public function add()
    {
        $this->checkAuth('friend:circle:add');
        if (Request::isGet()) {
            $info = [];
            $get  = input();
            if ($get['pcat_id'] != '') $info['pcat_id'] = $get['pcat_id'];
            if ($get['cat_id'] != '') $info['cat_id'] = $get['cat_id'];
            $this->assign('_info', $info);
            return $this->fetch();
        } else {
            $friend = new FriendCircleCircle();
            $post   = input();
            $result = $friend->backstageadd($post);
            if (!$result) $this->error($friend->getError());
            alog("friend.circle.add", "新增圈子 ID：".$result);
            $this->success('新增成功', $result);
        }
    }



}